### PR TITLE
Fe auth

### LINKED ISSUE #16: FE: Protected routes + auth calls
- Render protected pages conditionally to the user being logged in
- Use token to know whether user is authenticated 
- Create authFetch method that adds the token to the headers for protected requests. 
- On failed requests (403 Authorized): clear the token and user object, redirected user to login page

### PR DESCRIPTION
**Pull request by zeinabfarag-zz**
page should redirect to dashboard if signed in and signin if signed out. authfetch method for protected requests. 

removed starter unneeded components + routes

### CODE REVIEW

File: client/src/AuthService.js [hunk 1]
```diff
@@ -25,36 +33,32 @@ const getToken = () => {
...
 
 const _checkStatus = response => {
-  if (response.status >= 200 && response.status < 300) {
-    return response;
-  } else {
-    var error = new Error(response.statusText);
-    error.response = response;
-    throw error;
-  }
+  return response.json().then(res => {
```
Comment (aeciorc) [inline client/src/AuthService.js:50]: If it's an actual unexpected error, the response won't be in JSON, so this will throw an exception

**Review by aeciorc — CHANGES_REQUESTED** [review]

File: client/src/AuthService.js (hunk 1 above)
Comment (aeciorc) [reply client/src/AuthService.js:50]: wait nvm

Comment (aeciorc) [reply client/src/AuthService.js:50]: looks good actually, you can merge
